title: Introduction à la Cybersécurité - partie pratique
description: Énoncés des TP d'intro à la Cybersécurité 
theme: jekyll-theme-minimal
url: "https://ephec-tech.github.io" 
baseurl: "/intro-cybersecurite-pratique"

repository: echec-tech/intro-cybersecurite-pratique

# Menu de navigation (optionnel selon le thème, mais utile)
header_pages:
  - index.md
