title: Introduction à la Cybersécurité - partie pratique
description: Énoncés des TP d'intro à la Cybersécurité
remote_theme: just-the-docs/just-the-docs

# Configuration des URLs
url: "https://ephec-tech.github.io"
baseurl: "/intro-cybersecurite-pratique"

repository: ephec-tech/intro-cybersecurite-pratique

collections:
  seances:
    output: true
    permalink: /seances/:path/

# Paramètres du thème
aux_links:
  "Fiche EPHEC": "https://eperso.ephec.be/ProfFicheCoursHe/Visualiser/14794"

sass:
  style: compressed
