title: Introduction à la Cybersécurité - partie pratique
description: Énoncés des TP d'intro à la Cybersécurité
remote_theme: just-the-docs/just-the-docs

# Configuration des URLs
url: "https://ephec-tech.github.io"
baseurl: "/intro-cybersecurite-pratique"

repository: ephec-tech/intro-cybersecurite-pratique

collections:
  seances:
    output: true
    sort_by: order

# Si tu as un dossier _sass ou des assets personnalisés
sass:
  style: compressed
