title: Introduction à la Cybersécurité - partie pratique
description: Énoncés des TP d'intro à la Cybersécurité 
theme: jekyll-theme-minimal
url: "https://ephec-tech.github.io" 
baseurl: "/intro-cybersecurite-pratique"

# Configuration de la collection pour les cours
collections:
  seances:
    output: true
    sort_by: order # On triera par un champ 'order' dans le fichier

# Menu de navigation (optionnel selon le thème, mais utile)
header_pages:
  - index.md
